# L05 - Data Preprocessing and Machine Learning with Scikit-Learn

Importa a biblioteca do pandas, recupera os dados do arquivo "breast_cancer.csv" e atribui os dados a um DataFrame

In [1]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/jefferson-oliva/databases/main/breast_cancer.csv')
df.head()

sample_id  mean_radius  mean_texture  mean_perimeter  mean_area  \
0     842302        17.99         10.38          122.80     1001.0   
1     842517        20.57         17.77          132.90     1326.0   
2   84300903        19.69         21.25          130.00     1203.0   
3   84348301        11.42         20.38           77.58      386.1   
4   84358402        20.29         14.34          135.10     1297.0   

   mean_smoothness  mean_compactness  mean_concavity  mean_concave_points  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   mean_symmetry  ...  worst_texture  worst_perimeter  worst_area  \
0         0.2419  ...          17.33           184.60      2019.0   
1         0.1812  ...          23.41           158.80      1956.0   
2         0.2069  ...          25.53           152.50      1709.0   
3         0.2597  ...          26.50            98.87       567.7   
4         0.1809  ...          16.67           152.20      1575.0   

   worst_smoothness  worst_compactness  worst_concavity  worst_concave_points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst_symmetry  worst_fractal_dimension  diagnosis  
0          0.4601                  0.11890  malignant  
1          0.2750                  0.08902  malignant  
2          0.3613                  0.08758  malignant  
3          0.6638                  0.17300  malignant  
4          0.2364                  0.07678  malignant  

[5 rows x 32 columns]

Verifica a quantidade de linhas e colunas do DataFrame

In [2]:
df.shape

(569, 32)

Verifica quais os valores distintos da coluna "diagnosis"

In [3]:
df['diagnosis'].unique()

array(['malignant', 'benign'], dtype=object)

Cria um dicionário onde são armazenados valores númericos para cada valor distinto da coluna "diagnosis" e substitui os dados da coluna original do DataFrame pelos valores armazenados no dicionário

In [4]:
d = {'benign': 0, 
     'malignant': 1}

df['diagnosis'] = df['diagnosis'].map(d)
df.head()

sample_id  mean_radius  mean_texture  mean_perimeter  mean_area  \
0     842302        17.99         10.38          122.80     1001.0   
1     842517        20.57         17.77          132.90     1326.0   
2   84300903        19.69         21.25          130.00     1203.0   
3   84348301        11.42         20.38           77.58      386.1   
4   84358402        20.29         14.34          135.10     1297.0   

   mean_smoothness  mean_compactness  mean_concavity  mean_concave_points  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   mean_symmetry  ...  worst_texture  worst_perimeter  worst_area  \
0         0.2419  ...          17.33           184.60      2019.0   
1         0.1812  ...          23.41           158.80      1956.0   
2         0.2069  ...          25.53           152.50      1709.0   
3         0.2597  ...          26.50            98.87       567.7   
4         0.1809  ...          16.67           152.20      1575.0   

   worst_smoothness  worst_compactness  worst_concavity  worst_concave_points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst_symmetry  worst_fractal_dimension  diagnosis  
0          0.4601                  0.11890          1  
1          0.2750                  0.08902          1  
2          0.3613                  0.08758          1  
3          0.6638                  0.17300          1  
4          0.2364                  0.07678          1  

[5 rows x 32 columns]

Atribui os valores do Dataframe a uma nova variável, com exceção da primeira e última coluna 

In [5]:
X = df.iloc[:, 1:31].values
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

Atribui a uma nova variável os valores da coluna "diagnosis"

In [6]:
y = df['diagnosis'].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

Importa a biblioteca do numpy e a biblioteca train_test_split do sklearn. Através do método train_test_split() são sorteados, divididos proporcionalmente e armazenados em vaviáveis os dados de treino e teste. O método bincount() do numpy retorna a quantidade de ocorrências para cada valor armazenado na variável y_train

In [7]:
import numpy as np
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=123, stratify=y)
np.bincount(y_train)

array([285, 170], dtype=int64)

Importa a biblioteca StandardScaler do sklearn. O método fit() treina o modelo calculando a média e o desvio padrão dos dados para serem usados posteriormente. O método transform() realiza a padronização dos dados de forma centralizada e escalonada. 

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)
X_train_std = scaler.transform(X_train)
X_test_std = scaler.transform(X_test)
X_train_std

array([[ 0.1417264 , -0.82724427,  0.03393567, ..., -0.85351862,
        -0.61172434, -1.50761158],
       [-0.44025251, -0.68036206, -0.43122748, ..., -0.45813352,
         0.41854003, -0.48058782],
       [ 0.33571937,  1.40629783,  0.42950749, ...,  1.3421014 ,
         1.85596488,  0.82227792],
       ...,
       [-0.79450053, -1.36348089, -0.76697517, ..., -0.42769587,
        -1.31724938, -0.90075923],
       [-0.90696023, -0.84356451, -0.87237959, ..., -0.5258573 ,
        -0.52765476,  1.33718294],
       [ 0.8699029 ,  1.23143806,  0.90972842, ...,  1.15186607,
         0.67899086,  2.78047732]])

Importa a biblioteca KNeighborsClassifier do sklearn. O método fit() treina o modelo com base na classificação dos vizinhos mais próximos do conjunto de dados.

In [9]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=3)

knn_model.fit(X_train_std, y_train)

KNeighborsClassifier(n_neighbors=3)

O método predict() realiza a previsão das classes dos dados de teste

In [10]:
y_pred = knn_model.predict(X_test_std)
print(y_pred)
print(y_test)

[0 0 0 1 0 1 1 1 1 1 1 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 0
 0 0 1 1 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 1
 1 0 0 1 0 1 1 1 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0
 0 0 0]
[0 0 1 1 0 1 1 1 1 1 1 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 0 1 1 0
 0 0 1 1 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1
 1 0 0 1 0 1 1 1 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0
 0 0 0]


Importa a biblioteca accuracy_score do sklearn. O método accuracy_score() retorna a taxa de acerto entre os valores reais e os previstos

In [12]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.9736842105263158